#!/bin/sh
#
# launchmail - https://libslack.org/launchmail
#
# Copyright (C) 2000, 2023 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#
# 20230330 raf <raf@raf.org>
#

# A wrapper to make launchmail look like sendmail (http://www.sendmail.org/).
# Install this as /usr/sbin/sendmail - but only if you really mean it :)

usage="usage: $0 [options] address..."
launchmail="launchmail"

die() { echo "$@" >&2; exit 1; }

quote_check()
{
	case "$1" in
		*\'*)
			echo $usage >&2
			die "Sorry, I don't do single quotes: $1"
			;;
	esac
}

args=""
server="${SMTPSERVER:-localhost}"

# note: this doesn't handle options of the form: -ox value

while getopts "B:b:C:d:F:f:h:iL:N:nO:o:p:q:R:r:tUV:vX:" opt
do
	case $opt in
		\?) die $usage;;

		b)
			case "$OPTARG" in
				a|d|D|h|H|i|p|s|t|v)
					die "$0: This is not the real sendmail";;
			esac
			;;

		d) quote_check "$OPTARG"; args="$args '-d$OPTARG'";;
		f|r) quote_check "$OPTARG"; args="$args -f '$OPTARG'";;
		q) die "$0: This is not the real sendmail";;
		t) args="$args -r";;
		v) args="$args -v";;
	esac
done

shift `expr $OPTIND - 1`

for arg in ${1+"$@"}
do
	quote_check "$arg"
	args="$args -t '$arg'"
done

args="$args -q -N -S '$server'"

eval exec "$launchmail" $args

# vi:set ts=4 sw=4:
